### ISSUE TITLE
Gulpfile not found: ./gulpfile.js

### ISSUE THREAD

**Issue by johann04** [paulsutherland/Polyonic#13]
Just cloned the project, an when running "npm start" I got:

        Gulpfile not found: ./gulpfile.js
        You can set the gulpFile attribute in ionic.config.json for custom
        Gulpfile locations, otherwise the default Ionic Gulpfile can be
        downloaded from
        https://github.com/ionic-team/ionic-app-base/blob/master/gulpfile.js
        
        Or, if you no longer use gulp, you can remove the CLI Gulp Plugin:
        
        npm uninstall --save-dev --save-exact @ionic/cli-plugin-gulp@latest

**Comment by paulsutherland** [comment]
@johann04 

I can't replicate that error with a fresh clone.

Can you confirm the following please:

You ran the following commands:

```
git clone https://github.com/paulsutherland/Polyonic.git
cd Polyonic

npm install   <--- You get a gulp error if you have not run npm install
npm start
```

You have the gulpfile.js and tasks directory in your repo.

Thanks,

Paul

**Comment by johann04** [comment]
[polyonic.txt](https://github.com/paulsutherland/Polyonic/files/1163127/polyonic.txt)

**Comment by paulsutherland** [comment]
Thanks - that was helpful.

Can you please run ```ionic info``` and post back the output? I am wondering if you may need to update your Ionic CLI.

**Comment by paulsutherland** [comment]
@johann04 

You will need: 

The latest Node 6 LTS and NPM 3+ installed.

I think your Ionic CLI maybe needing an update to the latest version. Gulp has been dropped and replaced with [ionic-app-scripts](https://github.com/ionic-team/ionic-app-scripts)

`npm install -g ionic@latest`

I'll update the readme with the above dependencies.

Thanks,

Paul
