### ISSUE TITLE
Unable to find build or output binary file 

### ISSUE THREAD

**Issue by madlybong** [paulsutherland/Polyonic#14]
I'm using `gulp build` or `node_modules/.bin/build --win` command but it gives no windows binary file.

Also, `node_modules/.bin/build --win` gives error

> electron-builder 19.18.0
> Rebuilding native production dependencies for win32:x64
> Error: npm.cmd exited with code 1
> Output:
> 
> > leveldown@1.5.0 install E:\WORKZONE\GST MAGIC\Desktop\Polyonic\build\node_modules\leveldown
> > prebuild --install
> 
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [E:\WORKZONE\GST MAGIC\Desktop\Polyonic\build\node_modules\leveldown\deps\leveldb\leveldb.vcxproj]
> TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [E:\WORKZONE\GST MAGIC\Desktop\Polyonic\build\node_modules\leveldown\deps\leveldb\leveldb.vcxproj]
> 
> 
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [E:\WORKZONE\GST MAGIC\Desktop\Polyonic\build\node_modules\leveldown\deps\snappy\snappy.vcxproj]
> TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [E:\WORKZONE\GST MAGIC\Desktop\Polyonic\build\node_modules\leveldown\deps\snappy\snappy.vcxproj]
> 
> 
> 
> Error output:
> prebuild ERR! build error
> prebuild ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> prebuild ERR! stack     at ChildProcess.onExit (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\build\node_modules\node-gyp\lib\build.js:258:23)
> prebuild ERR! stack     at emitTwo (events.js:106:13)
> prebuild ERR! stack     at ChildProcess.emit (events.js:191:7)
> prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> prebuild ERR! not ok
> prebuild ERR! build Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> prebuild ERR! build     at ChildProcess.onExit (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\build\node_modules\node-gyp\lib\build.js:258:23)
> prebuild ERR! build     at emitTwo (events.js:106:13)
> prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
> prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> 
> npm ERR! Windows_NT 10.0.15063
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "leveldown"
> npm ERR! node v6.11.0
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! leveldown@1.5.0 install: `prebuild --install`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the leveldown@1.5.0 install script 'prebuild --install'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the leveldown package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     prebuild --install
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs leveldown
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls leveldown
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     E:\WORKZONE\GST MAGIC\Desktop\Polyonic\build\npm-debug.log
> 
>     at ChildProcess.childProcess.once.code (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder-util\src\util.ts:140:14)
>     at ChildProcess.g (events.js:292:16)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:891:16)
>     at Socket.<anonymous> (internal/child_process.js:342:11)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at Pipe._handle.close [as _onclose] (net.js:497:12)
> From previous event:
>     at spawn (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder-util\src\util.ts:103:3)
>     at E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\src\util\yarn.ts:171:5
> From previous event:
>     at rebuild (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\out\util\yarn.js:96:22)
>     at E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\src\util\yarn.ts:20:11
>     at next (native)
>     at runCallback (timers.js:672:20)
>     at tryOnImmediate (timers.js:645:5)
>     at processImmediate [as _immediateCallback] (timers.js:617:5)
> From previous event:
>     at installOrRebuild (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\out\util\yarn.js:34:21)
>     at E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\src\packager.ts:322:7
>     at next (native)
> From previous event:
>     at Packager.installAppDependencies (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\out\packager.js:381:11)
>     at E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\src\packager.ts:218:20
>     at next (native)
> From previous event:
>     at Packager.doBuild (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\out\packager.js:317:11)
>     at E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\src\packager.ts:175:52
>     at next (native)
>     at runCallback (timers.js:672:20)
>     at tryOnImmediate (timers.js:645:5)
>     at processImmediate [as _immediateCallback] (timers.js:617:5)
> From previous event:
>     at Packager.build (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\out\packager.js:236:11)
>     at E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\src\builder.ts:266:40
>     at next (native)
> From previous event:
>     at build (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\out\builder.js:69:21)
>     at Object.args [as handler] (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\src\cli\cli.ts:46:4)
>     at Object.self.runCommand (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\node_modules\yargs\lib\command.js:233:22)
>     at Object.Yargs.self._parseArgs (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\node_modules\yargs\yargs.js:1018:24)
>     at Object.get [as argv] (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\node_modules\yargs\yargs.js:927:19)
>     at Object.<anonymous> (E:\WORKZONE\GST MAGIC\Desktop\Polyonic\node_modules\electron-builder\src\cli\cli.ts:41:15)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:389:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:504:3

**Comment by paulsutherland** [comment]
Hi, sorry for the delay responding, I was on a summer holiday.

There area few issues here:

1. The path for the manifest was wrong for the windows release gulp script. I have corrected this and updated the repo.

2. For building on Windows you will need to install the Nullsoft Scriptable Install System.  

You can download NSIS <a href="http://nsis.sourceforge.net/Main_Page">here.</a>

You will need to make sure the NSIS path is added as an environment variable:
```
setx PATH "%PATH%;C:\Program Files (x86)\NSIS"
```

Or using <a href="http://nsis.sourceforge.net/Main_Page">point and click.</a>

I have updated the README with the NSIS requirements.

3. These updates highlighted a problem with the npm lint command as it will not run on windows due to the windows path requiring \ instead of /.  For now I have removed linting from the release script until I work out a cross platform solution.

I have pushed these changes, so please pull the latest repo. 

To build an exe, use the command:

```npm run release```

Let me know if that clears your issue.

Many Thanks,

Paul

**Comment by madlybong** [comment]
@paulsutherland Thanx... I really appreciate your work here... I'm using your Polyonic for one of my projects and would try to be active on its development here ...
