### ISSUE TITLE
Building .exe on mac

### ISSUE THREAD

**Issue by gciluffo** [paulsutherland/Polyonic#17]
Hi @paulsutherland 

Not sure if its just me, but I am having some issues building the project for windows on mac. Im looking at the gulp scripts .... by running `npm run release` it should generate a release version for all 3 platforms listed in './tasks/release/release' right? But currently it is only building for OSX. Are there are more detailed instructions covering this? Thanks in advance.

**Comment by paulsutherland** [comment]
Hi @gciluffo 

It is not setup for a multi platform build. It will build for the platform you are running on:

So run on macOS for a dmg, Windows for exe ...

See this [electron wiki article](https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build).

Thanks,

Paul
