### ISSUE TITLE
Build Info

### ISSUE THREAD

**Issue by gamboaweb** [paulsutherland/Polyonic#18]
First of all, congrats for the project Paul.
I'd like to know if you could give me some better direction on how to build the installer under Windows. I don't have much experience with electron so maybe i am missing some steps.
I cloned your project and was able to npm start the project with no problems then I tried to build the installer after reading some pages about how to build electron with electron-builder.
I noticed that polyonic shell already comes with electron-builder in package.json wich gets installed with npm install, right?
So to build the installer with electron-builder I use npm run dist...wich run the script define in package.json as dist, isn't that right? Okay... by doing electron-builder seems to start ok but I got errors right away.
There are no error with the ionic proj itself as I am trying with the standard proj and already tested with npm start and also with ionic serve inside the src directory.
I guess maybe it has to do with some extra config i should be typing in package.json?
I already installed NSIS in windows...do I have to refer to it in package.json some how?
Do you have any other comment I should be looking for?
Thanks in advance.

**Comment by paulsutherland** [comment]
If you could share the error output that would be handy.

For building on Windows you will need to install the Nullsoft Scriptable Install System.

You can download[ NSIS here](http://nsis.sourceforge.net/Main_Page).

You will need to make sure the NSIS path is added as an environment variable.  In a CMD prompt type:

`setx PATH "%PATH%;C:\Program Files (x86)\NSIS"`

To build an exe, use the command:

`npm run release`

Let me know if that clears your issue.

Many Thanks,

Paul

**Comment by gamboaweb** [comment]
Thanks a lot for your reply Paul.
I had forgotten to add NSIS environment path... after adding it and running npm run release, everything worked fine and now I have my own executable!!!
This is great...very excited about it. Have a great weekend.
