### ISSUE TITLE
Error at npm start

### ISSUE THREAD

**Issue by lapak10** [paulsutherland/Polyonic#19]
Followed the steps of installation with latest ionic and cordova.. produces this error
> polyonic@1.0.0 prestart /home/lucky/Polyonic
> cd src && ionic cordova build browser

[WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.
> cordova platform add browser --save
Using cordova-fetch for cordova-browser@4.1.0

Adding browser project...

Project already exists! Delete and recreate
[ERROR] Exception: 
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! polyonic@1.0.0 prestart: `cd src && ionic cordova build browser`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the polyonic@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lucky/.npm/_logs/2017-11-29T08_30_12_727Z-debug.log

**Here is the debug.log file content**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.5.1
3 info using node@v9.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle polyonic@1.0.0~prestart: polyonic@1.0.0
6 verbose lifecycle polyonic@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle polyonic@1.0.0~prestart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/lucky/Polyonic/node_modules/.bin:/home/lucky/$
8 verbose lifecycle polyonic@1.0.0~prestart: CWD: /home/lucky/Polyonic
9 silly lifecycle polyonic@1.0.0~prestart: Args: [ '-c', 'cd src && ionic cordova build browser' ]
10 silly lifecycle polyonic@1.0.0~prestart: Returned: code: 2  signal: null
11 info lifecycle polyonic@1.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: polyonic@1.0.0 prestart: `cd src && ionic cordova build browser`
12 verbose stack Exit status 2
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
12 verbose stack     at emitTwo (events.js:135:13)
12 verbose stack     at EventEmitter.emit (events.js:224:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at emitTwo (events.js:135:13)
12 verbose stack     at ChildProcess.emit (events.js:224:7)
12 verbose stack     at maybeClose (internal/child_process.js:943:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
13 verbose pkgid polyonic@1.0.0
14 verbose cwd /home/lucky/Polyonic
15 verbose Linux 4.13.0-17-generic
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v9.0.0
18 verbose npm  v5.5.1
19 error code ELIFECYCLE
20 error errno 2
21 error polyonic@1.0.0 prestart: `cd src && ionic cordova build browser`
21 error Exit status 2
22 error Failed at the polyonic@1.0.0 prestart script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 2, true ]

**Comment by paulsutherland** [comment]
Hi @lapak10 

I will be updating the project this weekend so I can look into it for you.

Can you please share the output of:

`ionic info`

That will let me know what your running.

**Comment by lapak10** [comment]
`ionic info` output
[WARN] You are not in an Ionic project directory. Project context may be 
       missing.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

System:

    Node : v9.0.0
    npm  : 5.5.1 
    OS   : Linux 4.13

Misc:

    backend : legacy

**Comment by iesous** [comment]
I omitted the prestart script from package.json and it started without problems. Not sure if this is required at all.

ionic info: 

cli packages: (C:\Users\AlienWare\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

System:

    Node : v6.9.2
    npm  : 5.5.1
    OS   : Windows 10

Misc:

    Backend: pro

**Comment by lapak10** [comment]
Fix provided by @iesous  worked for me ... 
@paulsutherland does prestart script contains any important code which might bug us later???

**Comment by paulsutherland** [comment]
@lapak10 @iesous 

Hi, the dependencies for the project were out of date, with regard to the latest Ionic CLI.  The specific problem was the version of the cordova-browser plugin.  Updating this to v5.0.1 resolved the issue.

I have, however, updated all dependencies for the project, so it is now running with the latest Electron and Ionic frameworks.

So, if you:

```
git clone https://github.com/paulsutherland/Polyonic.git
cd Polyonic

npm install
npm start  # or for development and live reload: npm run dev
```

You should be up and running.

Let me know if this resolves your build issue.

Cheers...

Paul

**Comment by lapak10** [comment]
@paulsutherland  issue fixed,I tried with a fresh install and its working fine now... closing the issue
