### ISSUE TITLE
native Menu not appearing in Browserwindow

### ISSUE THREAD

**Issue by lapak10** [paulsutherland/Polyonic#20]
**Aim**: To get native Menu Bar , like most of the electron apps have.
Current Output : No error in console, but not getting any Menu in browserwindow.
Steps: In file `Polyonic/src/app.js`  ( Changes in code can be [VIEWED HERE](https://www.diffnow.com/?report=sebj4)  )
1) Added ` const Menu = electron.Menu` after line `const electron = require('electron')`
2) Added a sample MenuItem `let template = [{
    label: 'Edit',
    submenu: [{
      label: 'Undo',
      accelerator: 'CmdOrCtrl+Z',
      role: 'undo'
    }, {
      label: 'Redo',
      accelerator: 'Shift+CmdOrCtrl+Z',
      role: 'redo'
    }, {
      type: 'separator'
    }, {
      label: 'Cut',
      accelerator: 'CmdOrCtrl+X',
      role: 'cut'
    }, {
      label: 'Copy',
      accelerator: 'CmdOrCtrl+C',
      role: 'copy'
    }, {
      label: 'Paste',
      accelerator: 'CmdOrCtrl+V',
      role: 'paste'
    }, {
      label: 'Select All',
      accelerator: 'CmdOrCtrl+A',
      role: 'selectall'
    }]
  }];`
3) In app.on-ready hook (around Line 76).... added `const menu = Menu.buildFromTemplate(template)
    Menu.setApplicationMenu(menu)`

**Copy** of my `Polyonic/src/app.js` can be found [HERE](https://pastebin.com/raw/c0tuCKPE)

**Comment by lapak10** [comment]
This was not an issue as I noticed there was `autoHideMenuBar: true` in `app.js` which when changed to `autoHideMenuBar: false` worked as expected.

**Comment by paulsutherland** [comment]
Thanks for feeding back and closing the issue. 🥇
