### ISSUE TITLE
leveldown@3.0.0.0 not compiling on npm install

### ISSUE THREAD

**Issue by xianve** [paulsutherland/Polyonic#32]
Dear Paul,

When I run npm install, I get lots of errors when lelvedown tries to compile.

Here is my ionic info output:
Ionic:

   Ionic CLI                     : 5.2.5 (C:\Users\chris\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

**Comment by paulsutherland** [comment]
@xianve 

Sorry for the delay.

Can you post the error message?

**Comment by paulsutherland** [comment]
@xianve 

Ok - hoping you are up and running now.  Closing this as I have not heard back.

If the problem persits, please open the issue again.

Cheers...

Paul
