### ISSUE TITLE
Main Process Debugging

### ISSUE THREAD

**Issue by rlaurente** [paulsutherland/Polyonic#34]
I just want to ask is there a way to debug main process ?

Thanks

**Comment by paulsutherland** [comment]
@rlaurente 

Yes there is, but the npm script was missing.

I have just pushed an update, so if you:

```git pull```

then 

```npm run electron:dev:debug```

You can drop a debugger statement in the electron.js file and debug the main process.  It will open the debugger in chrome dev tools. [You may want to look at the Chrome NiM add-on](https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj?hl=en).

Thanks,

Paul

**Comment by paulsutherland** [comment]
@rlaurente 

If that resolves debugging the main process, can you please let me know and I will close the issue.

Cheers...

Paul
