### ISSUE TITLE
Question: Port Electron to Ionic

### ISSUE THREAD

**Issue by cambo2015** [paulsutherland/Polyonic#36]
Will this work to port electron apps to ionic? I really need vs code on android and trying to look for a solution. T.I.A.

**Comment by paulsutherland** [comment]
@cambo2015 

No it would not be easy to do.  This app is a mobile framework that can run on the desktop.

If it is just a good code editor you require, you can add the [Ace Editor](https://ace.c9.io) to the app as a component?  That would allow you to run it on Android.

**Comment by cambo2015** [comment]
I found a solution using termux and black ice. If anybody is interested I downloaded termux from android and used this project: 
https://github.com/raynoppe/BLACKICEcoder
