### ISSUE TITLE
Package JSON prestart needs to use ionic cordova build browser

### ISSUE THREAD

**Issue by vicatcu** [paulsutherland/Polyonic#6]
The ionic CLI 3.0.0 (I'm at the latest which is 3.3.0) calls for explicitly saying cordova in the ionic command line. So in package.json you should change the line:
`"prestart": "cd src && ionic build",`
... to ...
`"prestart": "cd src && ionic cordova build browser",`

**Comment by vicatcu** [comment]
fwiw, `"ionic:build": "ionic-app-scripts build"` I don't think technically works either as in you can't type `npm run ionic:build` because you get `sh: 1: ionic-app-scripts: not found`

**Comment by paulsutherland** [comment]
Thanks, I was using a slightly older Ionic CLI.

I have updated both and tested it with the latest Ionic CLI and it works fine.

Cheers..

Paul
