### ISSUE TITLE
Cordova is considered out of support

### ISSUE THREAD

**Issue by alexandruchirita4192** [paulsutherland/Polyonic#80]
Hi,

I believe that maybe this application should migrate from Cordova to something else, because:
"In April 2022, Microsoft App Center deprecated Cordova support, a true sign of the waning popularity of the framework."

What do you think? Is it a non-issue? Would it still have a future if Cordova is out of support?

Source of the statement:
https://ionic.io/blog/signs-its-time-to-migrate-your-cordova-app

Migrating guide from Cordova to Capacitor:
https://capacitorjs.com/docs/cordova/migrating-from-cordova-to-capacitor

Good luck! Have a nice day!

**Comment by paulsutherland** [comment]
Hi @alexandruchirita4192 

Thanks for raising this.

I think you are right, but I have not been maintaining this project for some time and will look to archive it unless there was interest from the wider community.

Cheers...

Paul
